name: Upload to S3 buckets

on:
    push:
      branches:
        - main
      paths:
        - 'frontend/**'
        - '.github/workflows/cicd_frontend.yml'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source code
      uses: actions/checkout@v3
    - name: Sync S3
      uses: jakejarvis/s3-sync-action@master
      env:
        SOURCE_DIR: './frontend'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: 'teepswebucket'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}