name: Upload to S3

on:
    push:
      branches:
        - main
      paths:
        - 'frontend/**'
        - '.github/workflows/cicd_frontend.yml'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: teepsWebucket
          source_dir: 'frontend'